Repository googleapis/java-logging, pull requests merged in 2020-10, with the labels that each got.

#274 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#280 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#284 chore: Add cdpe ops team to codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: logging, automerge, cla: yes, lang: java, priority: p2

#285 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full, samples

#286 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#296 chore: regenerate common templates
  .github/CODEOWNERS
  .github/snippet-bot.yml
  .github/workflows/approve-readme.yaml
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  renovate.json
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: partial

#300 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#301 test: fix list logs test flakiness
  .github/CODEOWNERS
  .readme-partials.yaml
  README.md
  google-cloud-logging/pom.xml
  google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntry.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/Logging.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingLevel.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/Metric.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/MetricInfo.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/Sink.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/SinkInfo.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/Synchronicity.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/package-info.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/LoggingRpc.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/testing/package-info.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/BaseSystemTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingHandlerTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITLoggingTest.java
  samples/snapshot/pom.xml
  samples/snippets/src/main/java/com/example/logging/ListLogs.java
  samples/snippets/src/main/java/com/example/logging/QuickstartSample.java
  samples/snippets/src/main/resources/logging.properties
Labels: api: logging, automerge, cla: yes, priority: p1, type: cleanup

#294 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, cla: yes

#306 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#309 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
