Repository googleapis/java-logging, pull requests merged in 2020-11, with the labels that each got.

#307 chore: regenerate common templates
  .github/CODEOWNERS
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: logging, cla: yes, context: partial

#312 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#313 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: logging, cla: yes, context: full, priority: p2, type: process

#315 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#316 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: api: logging, cla: yes, priority: p2, type: process

#162 feat: expose log exclusion apis
  google-cloud-logging/clirr-ignored-differences.xml
  google-cloud-logging/pom.xml
  google-cloud-logging/src/main/java/com/google/cloud/logging/Exclusion.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/Logging.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/GrpcLoggingRpc.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/LoggingRpc.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/ExclusionTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java
Labels: cla: yes

#318 chore: assign both PRs and issues to repo owner
  .github/blunderbuss.yml
Labels: api: logging, cla: yes, priority: p2

#319 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: logging, cla: yes, context: full, priority: p2

#304 fix: add default time range filter for ListLogEntries API
  google-cloud-logging/src/main/java/com/google/cloud/logging/ITimestampDefaultFilter.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/TimestampDefaultFilter.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/TimestampDefaultFilterTest.java
Labels: api: logging, cla: yes, lang: java, priority: p2, type: bug

#322 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#325 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#328 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#333 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#334 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: logging, cla: yes, context: partial

#335 chore(samples): fix version replacement tags
  samples/install-without-bom/pom.xml
Labels: api: logging, cla: yes

#338 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, cla: yes, context: full

#340 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes, priority: p2, type: process

#345 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#346 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full, samples
