Repository googleapis/java-logging, pull requests merged in 2020-12, with the labels that each got.

#349 [CHANGE ME] Re-generated to pick up changes from googleapis.
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/LoggingClientTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockLoggingServiceV2Impl.java
  grpc-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LoggingServiceV2Grpc.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesRequest.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesRequestOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogsRequest.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogsRequestOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LoggingProto.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/TailLogEntriesRequest.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/TailLogEntriesRequestOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/TailLogEntriesResponse.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/TailLogEntriesResponseOrBuilder.java
  proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/logging.proto
  synth.metadata
Labels: api: logging, cla: yes, context: full

#343 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#353 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: logging, cla: yes, context: full, type: docs

#24 feat: fix resourceNames
  google-cloud-logging/src/main/java/com/google/cloud/logging/Logging.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingTest.java
Labels: api: logging, cla: yes, priority: p2, type: bug

#207 feat: add support for k8s_container resource type
  google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingHandlerTest.java
Labels: api: logging, cla: yes

#356 docs: specify current version
  README.md
Labels: api: logging, cla: yes

#360 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#361 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#364 chore: the versions in install-without-bom should be updated by renovate-bot only
  samples/install-without-bom/pom.xml
Labels: api: logging, cla: yes, lang: java, type: process

#365 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes, lang: java, priority: p2, type: docs

#370 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#377 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#378 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#381 chore: cleanup ignored differences
  google-cloud-logging/clirr-ignored-differences.xml
  grpc-google-cloud-logging-v2/clirr-ignored-differences.xml
Labels: api: logging, cla: yes

#384 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full, merge
