Repository googleapis/java-logging, pull requests merged in 2020-09, with the labels that each got.

#205 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full

#201 fix: update retry settings
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/package-info.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  grpc-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ConfigServiceV2Grpc.java
  grpc-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LoggingServiceV2Grpc.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/BigQueryOptions.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/BigQueryOptionsOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CmekSettings.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CmekSettingsOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/GetCmekSettingsRequest.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesRequest.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesRequestOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntry.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntryOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogExclusion.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogExclusionOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogMetric.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogMetricOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogSink.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogSinkOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LoggingProto.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateCmekSettingsRequest.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateCmekSettingsRequestOrBuilder.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesRequest.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesRequestOrBuilder.java
  proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/log_entry.proto
  proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/logging.proto
  proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/logging_config.proto
  proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/logging_metrics.proto
  synth.metadata
Labels: cla: yes, context: full

#225 test: split tests by resource type. fix query time by limiting by timestamp
  google-cloud-logging/src/test/java/com/google/cloud/logging/BaseSystemTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITJulLoggerTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITLoggingTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITMetricsTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITSinkTest.java
Labels: cla: yes

#226 feat: add logging bucket destination for log sinks
  google-cloud-logging/src/main/java/com/google/cloud/logging/SinkInfo.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/SinkInfoTest.java
Labels: cla: yes

#230 Release java-logging v1.102.0
  README.md
  google-cloud-logging-bom/pom.xml
  google-cloud-logging/pom.xml
  grpc-google-cloud-logging-v2/pom.xml
  pom.xml
  proto-google-cloud-logging-v2/pom.xml
  samples/install-without-bom/pom.xml
  samples/snippets/pom.xml
  versions.txt
Labels: api: logging, autorelease: pending, cla: yes

#227 samples: limit list log in samples
  samples/install-with-bom/pom.xml
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/logging/ListLogs.java
Labels: api: logging, automerge, cla: yes

#212 fix: make TransportChannel autocloseable
  google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/GrpcLoggingRpc.java
Labels: api: logging, cla: yes

#228 chore: regenerate README
  README.md
  synth.metadata
Labels: api: logging, cla: yes, context: none

#236 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: logging, cla: yes, context: none

#240 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .github/workflows/samples.yaml
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  .kokoro/release/stage.cfg
  samples/snippets/src/main/java/com/example/logging/ListLogs.java
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#255 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#259 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: logging, automerge, cla: yes

#260 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#265 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#267 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
