Repository googleapis/java-logging, pull requests merged in 2021-08, with the labels that each got.

#600 ci: remove java 7 units check
  .github/sync-repo-settings.yaml
Labels: api: logging, cla: yes

#604 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: api: logging, cla: yes

#603 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: logging, cla: yes

#599 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#587 feat: deprecate methods
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CmekSettingsName.java
  synth.metadata
  synth.py
Labels: api: logging, automerge, cla: yes

#605 feat!: release gapic-generator-java v2.0.0
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/MetricsClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/MetricsSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/ConfigClientTest.java
Labels: api: logging, automerge, cla: yes, context: full

#609 chore: fix checker-qual dependency issue
  pom.xml
Labels: api: logging, automerge, cla: yes

#613 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#610 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, api: logging, context: full

#622 chore(doc): fix duplicated region tag
  samples/snippets/src/main/java/com/example/logging/ListLogs.java
Labels: cla: yes, api: logging

#623 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#624 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: logging, context: full

#626 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#629 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#634 chore(README): update package name
  README.md
Labels: cla: yes, api: logging

#635 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#637 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: logging, automerge

#651 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge
