Repository googleapis/java-logging, pull requests merged in 2021-04, with the labels that each got.

#486 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#488 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#490 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#491 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#496 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#499 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#493 test: fix logging tests
  .github/CODEOWNERS
  google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/SinkInfo.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITLoggingTest.java
Labels: api: logging, cla: yes

#501 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#515 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#516 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes
