Repository googleapis/java-logging, pull requests merged in 2021-02, with the labels that each got.

#413 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: logging, cla: yes, context: partial

#414 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#366 chore: migrate to microgenerator
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/MetricsClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/MetricsSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/package-info.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/ConfigClientTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/LoggingClientTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MetricsClientTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockConfigServiceV2.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockConfigServiceV2Impl.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockLoggingServiceV2.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockLoggingServiceV2Impl.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockMetricsServiceV2.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockMetricsServiceV2Impl.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/BillingAccountLocationName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/BillingAccountName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CmekSettingsName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/FolderLocationName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/FolderName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LocationName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogBucketName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogExclusionName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogMetricName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogSinkName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogViewName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/OrganizationLocationName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/OrganizationName.java
  proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ProjectName.java
  synth.metadata
  synth.py
Labels: api: logging, cla: yes, context: full

#415 chore: Re-generated to pick up changes from googleapis
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/MetricsClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2CallableFactory.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MetricsClientTest.java
  synth.metadata
Labels: api: logging, cla: yes, context: full

#416 chore: Re-generated to pick up changes from synthtool
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: logging, cla: yes, context: full

#425 tests: fix flaky test
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITLoggingTest.java
Labels: api: logging, cla: yes

#427 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#429 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#423 docs: generate sample code in the Java microgenerator
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/MetricsClient.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/package-info.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full, samples

#435 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#434 chore: update gapic-generator-java to 0.0.20
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2Stub.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2Stub.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/ConfigClientTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockConfigServiceV2Impl.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockLoggingServiceV2Impl.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockMetricsServiceV2Impl.java
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#436 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#437 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#438 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#440 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/gapic_metadata.json
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#444 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#445 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#447 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#453 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes
