Repository googleapis/java-logging, pull requests merged in 2021-01, with the labels that each got.

#386 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#394 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#395 chore: add back blunderbuss configs overridden by yoshi-automation
  .github/blunderbuss.yml
Labels: api: logging, cla: yes, priority: p2

#367 samples: Add an HTTPRequest log sample
  README.md
  samples/snippets/src/main/java/com/example/logging/LogEntryWriteHttpRequest.java
  samples/snippets/src/test/java/com/example/logging/LoggingIT.java
Labels: api: logging, cla: yes, samples, type: docs

#396 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#383 samples: add getSinkMetadata sample
  samples/snippets/src/main/java/com/example/logging/GetSinkMetadata.java
  samples/snippets/src/test/java/com/example/logging/SinkIT.java
Labels: api: logging, cla: yes, samples

#397 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#400 chore: Update synth.py to exclude codeowners
  .github/CODEOWNERS
  google-cloud-logging/src/main/java/com/google/cloud/logging/SinkInfo.java
  synth.py
Labels: api: logging, automerge, cla: yes, priority: p1, type: bug, type: cleanup

#404 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#408 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#409 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: logging, cla: yes
