Repository googleapis/java-logging, pull requests merged in 2021-07, with the labels that each got.

#574 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#575 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#576 chore: remove distributionManagement section
  google-cloud-logging-bom/pom.xml
Labels: api: logging, automerge, cla: yes

#579 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#578 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#583 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#584 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#582 fix: describe authorization required for service object
  .readme-partials.yaml
  README.md
Labels: api: logging, cla: yes, type: docs

#591 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#595 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#596 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes
