Repository googleapis/java-logging, pull requests merged in 2021-09, with the labels that each got.

#654 fix(598): Change timestamp type to support nanosecond resolution
  google-cloud-logging/src/main/java/com/google/cloud/logging/JavaTimeConversions.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntry.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/LogEntryTest.java
Labels: cla: yes, api: logging

#656 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#662 ci: update CI to use maven 3.8.1
  .github/workflows/ci.yaml
Labels: cla: yes, api: logging

#630 chore: update gapic-generator-java version to 2.1.0
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  synth.metadata
Labels: cla: yes, api: logging, context: full

#663 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: logging, automerge

#666 doc: add information about writing log entry modes
  README.md
Labels: cla: yes, api: logging

#670 chore(fix): imrpove exec time of flaky test
  samples/snippets/src/main/java/com/example/logging/ListLogEntries.java
  samples/snippets/src/test/java/com/example/logging/LoggingIT.java
Labels: cla: yes, api: logging

#644 ci: removing linkage-monitor from the required checks
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  renovate.json
  synth.metadata
Labels: cla: yes, api: logging, automerge, context: full, context: partial

#641 fix: Return Resource.K8sContainer when autodetecting resource type
  google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java
Labels: cla: yes, api: logging

#669 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  google-cloud-logging-bom/pom.xml
  google-cloud-logging/pom.xml
  owlbot.py
  pom.xml
  synth.py
  versions.txt
Labels: cla: yes, api: logging

#628 feat: Add a sample snippet for use of the tailLogEntries API
  README.md
  google-cloud-logging/src/main/java/com/google/cloud/logging/JavaTimeConversions.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntryIterator.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntryServerStream.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/TailLogEntriesTest.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/it/ITTailLogsTest.java
  samples/snippets/src/main/java/com/example/logging/TailLogEntries.java
  samples/snippets/src/test/java/com/example/logging/LoggingIT.java
Labels: cla: yes, api: logging, samples

#674 chore(fix): fix region tag
  samples/snippets/src/main/java/com/example/logging/TailLogEntries.java
Labels: cla: yes, api: logging, automerge

#675 chore (doc): update readme partial template
  .readme-partials.yaml
Labels: cla: yes, api: logging

#677 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: logging, automerge

#615 fix: add space to fix embedding exclusion in docs
  samples/snippets/pom.xml
Labels: type: docs, cla: yes, api: logging

#696 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: logging, automerge

#700 chore: change branch master to main in github configurations
  .github/blunderbuss.yml
  README.md
Labels: cla: yes, api: logging, automerge
