Repository googleapis/java-logging, pull requests merged in 2024-01, with the labels that each got.

#1497 chore(.github): Update logback issues and prs assignee
  .github/blunderbuss.yml
  README.md
Labels: api: logging, size: xs

#1501 fix: Replace internal Structs class with google-cloud-core version
  google-cloud-logging/src/main/java/com/google/cloud/logging/Payload.java
  google-cloud-logging/src/main/java/com/google/cloud/logging/Structs.java
  google-cloud-logging/src/test/java/com/google/cloud/logging/StructsTest.java
  pom.xml
Labels: api: logging, size: l

#1507 chore: remove obsolete release job configs
  .kokoro/release/bump_snapshot.cfg
  .kokoro/release/bump_snapshot.sh
  .kokoro/release/common.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.cfg
  .kokoro/release/drop.sh
  .kokoro/release/promote.cfg
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/snapshot.cfg
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  .kokoro/requirements.in
  .kokoro/requirements.txt
  README.md
  owlbot.py
Labels: api: logging, size: xl

#1523 chore: use sdk-platform-shared-config to consolidate build configs
  .kokoro/presubmit/graalvm-native-17.cfg
  .kokoro/presubmit/graalvm-native.cfg
  owlbot.py
  pom.xml
Labels: api: logging, size: s
